import { PropsWithChildren } from "react";
import "./globals.css";
import { Toaster } from "sonner";
import { SocketProvider } from "./components/context/SocketContext";
import { ApolloWrapper } from "./components/providers";

export const metadata = {
  title: "Welcome to example-frontend",
  description: "Generated by create-nx-workspace",
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html className="h-full" lang="en">
      <body className="h-full">
        <SocketProvider>
          <ApolloWrapper>{children}</ApolloWrapper>
        </SocketProvider>
      </body>
    </html>
  );
};

export default RootLayout;
