import { PropsWithChildren } from "react";
import "./globals.css";
import { ApolloWrapper } from "./components/providers";
// import { Toaster } from "sonner";
// import { ApolloWrapper } from "./components/providers";

export const metadata = {
  title: "Welcome to example-frontend",
  description: "Generated by create-nx-workspace",
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          {children}
          {/* <Toaster /> */}
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
