import { PropsWithChildren } from "react";
import "./globals.css";
import { Toaster } from "sonner";
import { ApolloWrapper } from "./components/providers";
import { UserProvider } from "@/lib/userProvider";

export const metadata = {
  title: "Welcome to example-frontend",
  description: "Generated by create-nx-workspace",
};

const RootLayout = ({ children }: PropsWithChildren) => {
   const userId = 1
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <UserProvider userId={userId}>{children}</UserProvider>
          <Toaster />
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
